# EJERCICIOS CUESTIONARIO KD-TREES

Question 2
Questions 2, 3, 4, and 5 involves training a KD-tree on the following dataset:
```
              
              +----------------------+----------------------+
              |          X1          |         X2           |
|-------------+----------------------+----------------------+
|Data point 1 |         -1.58        |       -2.01          |
|-------------+----------------------+----------------------+
|Data point 2 |          0.91        |        3.98          |
|-------------+----------------------+----------------------+
|Data point 3 |         -0.73        |        4.00          |
|-------------+----------------------+----------------------+
|Data point 4 |         -4.22        |        1.16          |
|-------------+----------------------+----------------------+
|Data point 5 |          4.19        |       -2.02          |
|-------------+----------------------+----------------------+
|Data point 6 |         -0.33        |        2.15          |
|-------------+----------------------+----------------------+

```
Train a KD-tree by hand as follows:

First split using X1 and then using X2. Alternate between X1 and X2 in order.

Use “middle-of-the-range” heuristic for each split. Take the maximum and minimum of the coordinates of the member points.

Keep subdividing until every leaf node contains two or fewer data points.

In [1]:
import numpy as np

x1 = np.array([-1.58, 0.91, -0.73, -4.22, 4.19, -0.33])
x2 = np.array([-2.01, 3.98, 4.00, 1.16, -2.02, 2.15])

x = np.vstack((x1, x2)).T
x

array([[-1.58, -2.01],
       [ 0.91,  3.98],
       [-0.73,  4.  ],
       [-4.22,  1.16],
       [ 4.19, -2.02],
       [-0.33,  2.15]])

In [6]:
# Mid range of x1
x1_midrange = (x1.max() + x1.min())/2
x1_midrange

-0.01499999999999968

## What is the split value used for the first split? Enter the exact value, as you are expected to obtain a finite number of decimals. Use American-style decimals (e.g. 0.026).


**R/:** -0.015

In [3]:
def get_mid_range(data, column=0):
    """ Get midrange of data by column
    - x1: column=0
    - x2: column=1
    """
    midrange = (data[:, column].max() + data[:, column].min())/2
    return midrange      

def split_by(x, value, column=0):
    """ Split x array by value and column
    - x1: column=0
    - x2: column=1
    """
    split1 = x[x[:, column] <= value]
    split2 = x[x[:, column] > value]
    return split1, split2

In [4]:
x1_midrange = get_mid_range(x)
x1_split1, x1_split2 = split_by(x, x1_midrange)

# Split values of x1
x1_split1

array([[-1.58, -2.01],
       [-0.73,  4.  ],
       [-4.22,  1.16],
       [-0.33,  2.15]])

In [5]:
# Split values of x1
x1_split2

array([[ 0.91,  3.98],
       [ 4.19, -2.02]])

## What is the split value used for the second split? Enter the exact value, as you are expected to obtain a finite number of decimals. Use American-style decimals (e.g. 0.026).

**R/:** 0.995

In [7]:
# Mid range of x2 for the 1st split
# x1_split1_x2_midrange = (x1_split1[:, 1].max() + x1_split1[:, 1].min())/2
x1_split1_x2_midrange = get_mid_range(x1_split1, column=1)

print (x1_split1_x2_midrange)

0.9950000000000001


In [8]:
# # Mid range of x2 for 2nd split
x1_split2_x2_midrange = get_mid_range(x1_split2, column=1)
print (x1_split2_x2_midrange)

0.98


## Given a query point (-3, 1.5), which of the data points belong to the same leaf node as the query point? Choose all that apply.

- Data point 1
- Data point 2  
- Data point 3
- Data point 4
- Data point 5
- Data point 6

**R/:** DATA POINT 4

In [10]:
x1_split1_x2_split1, x1_split1_x2_split2 = split_by(x1_split1, x1_split1_x2_midrange, column=1)
x1_split1_x2_split1

array([[-1.58, -2.01]])

In [11]:
# node still has 3 data points
# continue to split

x1_split1_x2_split2 

array([[-0.73,  4.  ],
       [-4.22,  1.16],
       [-0.33,  2.15]])

In [12]:
x1_split1_x2_split2_midrange = get_mid_range(x1_split1_x2_split2, column=1)
x1_split1_x2_split2_midrange

2.58

In [13]:
x1_split1_x2_split2_x2_split1, x1_split1_x2_split2_x2_split2 = split_by(x1_split1_x2_split2, 
                                                                        x1_split1_x2_split2_midrange, 
                                                                        column=1)
x1_split1_x2_split2_x2_split1
# Continue to split

array([[-4.22,  1.16],
       [-0.33,  2.15]])

In [14]:
x1_split1_x2_split2_x2_split2

array([[-0.73,  4.  ]])

In [15]:
x1_split1_x2_split2_x2_split1_midrange = get_mid_range(x1_split1_x2_split2_x2_split1, column=1)
x1_split1_x2_split2_x2_split1_midrange

1.6549999999999998

## After split x1_split1_x2_split2_x2_split1 by 1.654, then we will have 2 more leaves. Data point 4: [-4.22, 1.16] will be the leaves contain the query point (-3, 1.5)

## Perform backtracking with the query point (-3, 1.5) to perform exact nearest neighbor search. Which of the data points would be pruned from the search? Choose all that apply.

Hint: Assume that each node in the KD-tree remembers the tight bound on the coordinates of its member points, as follows:



In [16]:
x1_split2_x2_split1, x1_split2_x2_split2 = split_by(x1_split2, x1_split2_x2_midrange, column=1)
x1_split2_x2_split1

array([[ 4.19, -2.02]])

In [17]:
x1_split2_x2_split2

array([[0.91, 3.98]])

## COMPARACION K-MEANS Y EM

In [27]:
import numpy as np
import turicreate as tc
import scipy
from scipy.stats import multivariate_normal #función de densidad de probabilidad (PDF) de la distribución gaussiana subyacente

## E-step: calcular las responsabilidades del clúster, dados los parámetros del clúster

In [12]:
#el punto de datos 0, la PDF de la distribución gaussiana para el conglomerado A tiene un valor de
print (scipy.stats.multivariate_normal.pdf([10,5], mean=[3,4], cov=[[3,0],[0,3]]))

#El valor que hay en mean(3,4) es la coordenada del centroide

1.275199678019219e-05


In [13]:
#el punto de datos 0, la PDF de la distribución gaussiana para el conglomerado A tiene un valor ponderado de
print (1/3*scipy.stats.multivariate_normal.pdf([10,5], mean=[3,4], cov=[[3,0],[0,3]]))

4.250665593397396e-06


In [14]:
#el punto de datos 0, la PDF de la distribución gaussiana para el conglomerado B tiene un valor ponderado de
print (1/3*scipy.stats.multivariate_normal.pdf([10,5], mean=[6,3], cov=[[3,0],[0,3]]))

0.0006308547090047343


In [15]:
#el punto de datos 0, la PDF de la distribución gaussiana para el conglomerado C tiene un valor ponderado de
print (1/3*scipy.stats.multivariate_normal.pdf([10,5], mean=[4,6], cov=[[3,0],[0,3]]))

3.710464810267033e-05


### Claramente, el grupo B tiene la medida de probabilidad más alta. Esto tiene sentido porque el punto de datos 0 está más cerca del centro del grupo B que otros.

In [19]:
suma = 4.250665593397396e-06 + 0.0006308547090047343 + 3.710464810267033e-05
suma

0.000672210022700802

### responsabilidades del clúster para el punto de datos 0!

El mayor valor con un 93% de pertenencia del dato 0 al cluster B

In [18]:
responsabilidad_1 = 4.250665593397396e-06 / suma
responsabilidad_2 = 0.0006308547090047343 / suma
responsabilidad_3 = 3.710464810267033e-05 / suma

print (responsabilidad_1)
print (responsabilidad_2)
print (responsabilidad_3)

0.0063234189462381026
0.9384785821402803
0.05519799891348163


## Para el punto de datos 1

In [20]:
print (1/3*scipy.stats.multivariate_normal.pdf([2,1], mean=[3,4], cov=[[3,0],[0,3]]))
print (1/3*scipy.stats.multivariate_normal.pdf([2,1], mean=[6,3], cov=[[3,0],[0,3]]))
print (1/3*scipy.stats.multivariate_normal.pdf([2,1], mean=[4,6], cov=[[3,0],[0,3]]))


0.0033400539801177326
0.0006308547090047343
0.00014076271225061746


In [21]:
suma = 0.0033400539801177326 + 0.0006308547090047343 + 0.00014076271225061746
suma

responsabilidad_1 = 0.0033400539801177326 / suma
responsabilidad_2 = 0.0006308547090047343 / suma
responsabilidad_3 = 0.00014076271225061746 / suma

print (responsabilidad_1)
print (responsabilidad_2)
print (responsabilidad_3)

0.8123348521971693
0.15343023491470198
0.03423491288812866


## Para el punto de datos 2

In [22]:
print (1/3*scipy.stats.multivariate_normal.pdf([3,7], mean=[3,4], cov=[[3,0],[0,3]]))
print (1/3*scipy.stats.multivariate_normal.pdf([3,7], mean=[6,3], cov=[[3,0],[0,3]]))
print (1/3*scipy.stats.multivariate_normal.pdf([3,7], mean=[4,6], cov=[[3,0],[0,3]]))

0.003945807548945426
0.0002741683263617117
0.012671055550881397


In [25]:
suma = 0.003945807548945426 + 0.0002741683263617117 + 0.012671055550881397
suma

responsabilidad_1 = 0.003945807548945426 / suma
responsabilidad_2 = 0.0002741683263617117 / suma
responsabilidad_3 = 0.012671055550881397 / suma

print (responsabilidad_1)
print (responsabilidad_2)
print (responsabilidad_3)

0.2336037065698479
0.016231591750911677
0.7501647016792403


In [30]:
ex_sframe = tc.SFrame()
ex_sframe['Matriz de responsabilidad'] = 'punto de datos 0','punto de datos 1','punto de datos 2','Conteos suaves'
ex_sframe['Cluster A'] = 0.007,0.812,0.234,1.053
ex_sframe['Cluster B'] = 0.938,0.154,0.016,1.108
ex_sframe['Cluster C'] = 0.055,0.034,0.750,0.839

print (ex_sframe)

+---------------------------+-----------+-----------+-----------+
| Matriz de responsabilidad | Cluster A | Cluster B | Cluster C |
+---------------------------+-----------+-----------+-----------+
|      punto de datos 0     |   0.007   |   0.938   |   0.055   |
|      punto de datos 1     |   0.812   |   0.154   |   0.034   |
|      punto de datos 2     |   0.234   |   0.016   |    0.75   |
|       Conteos suaves      |   1.053   |   1.108   |   0.839   |
+---------------------------+-----------+-----------+-----------+
[4 rows x 4 columns]



## M-step: Compute los parámetros del clúster, dadas las responsabilidades del clúster

In [31]:
#CALCULAMOS LOS PORCENTAJES DE LOS CONTEOS SUAVES QUE SERAN LOS NUEVOS PESOS DE LOS CLUSTERS

suma = 1.053 + 1.108 + 0.839 
conteoA = 1.053 / suma
conteoB = 1.108 / suma
conteoC = 0.839 / suma

print (conteoA)
print (conteoB)
print (conteoC)

0.351
0.36933333333333335
0.2796666666666667


### Means. Primero agregamos partes fraccionarias de todos los puntos de datos, usando las responsabilidades del grupo:

[Weighted sum of data points for cluster A] =

[Fraction of data point 0 represented in cluster A] * [data point 0] +
[Fraction of data point 1 represented in cluster A] * [data point 1] +
[Fraction of data point 2 represented in cluster A] * [data point 2]

= 0.007*[data point 0] + 0.812*[data point 1] + 0.234*[data point 2]

In [36]:
#0.007*(10,5)
print (0.007*10,0.007*5)

#0.812*(2,1)
print(0.812*2,0.812*1)

#0.234*(3,7)
print (0.234*3,0.234*7)

0.07 0.035
1.624 0.812
0.7020000000000001 1.6380000000000001


In [38]:
print (0.07 + 1.624 + 0.702)
print (0.035 + 0.812 + 1.638)

#Luego dividimos esta suma por el conteo suave:

print ((0.07 + 1.624 + 0.702)/1.053)
print ((0.035 + 0.812 + 1.638)/1.053)

2.396
2.485
2.275403608736942
2.359924026590693


### Repitiendo este proceso para el cluster B y C, obtenemos la nueva estimación de medias:

In [39]:
ex_sframe = tc.SFrame()
ex_sframe['Nuevas medias'] = 'Cluster A','Cluster B','Cluster C'
ex_sframe['X'] = 2.275,8.787,3.418
ex_sframe['Y'] = 2.360,4.473,6.626

print (ex_sframe)

+---------------+-------+-------+
| Nuevas medias |   X   |   Y   |
+---------------+-------+-------+
|   Cluster A   | 2.275 |  2.36 |
|   Cluster B   | 8.787 | 4.473 |
|   Cluster C   | 3.418 | 6.626 |
+---------------+-------+-------+
[3 rows x 3 columns]



### Calcular las covarianzas

$$
(x_i - \hat{\mu_k})*(x_i - \hat{\mu_k})^T
$$
$$
x_0 - \hat{\mu_A} = (10,5)-(2.275,2.360)=(7.725, 2.640)
$$
$$
x_1 - \hat{\mu_A} = (2,1)-(2.275,2.360)=(-0.275,-1.360)
$$
$$
x_2 - \hat{\mu_A} = (3,7)-(2.275,2.360)=(0.725,4.640)
$$

### Luego calculamos tres productos externos. Tenga en cuenta que los productos exteriores son realmente matrices de dos por dos.

$$
(x_0 - \hat{\mu_A})*(x_0 - \hat{\mu_A})^T  = [[7.725], [2.640]] * [[7.725,2.640]] = [[59.676,20.394], [20.394,6.970]]
$$
$$
(x_1 - \hat{\mu_A})*(x_1 - \hat{\mu_A})^T  = [[-0.275], [-1.360]] * [[-0.275,-1.360]] = [[0.076,0.374], [0.374,1.850]]
$$
$$
(x_2 - \hat{\mu_A})*(x_2 - \hat{\mu_A})^T  = [[0.725], [4.640]] * [[0.725,4.640]] = [[0.526,3.364], [3.364,21.530]]
$$

### Finalmente, tomamos el promedio ponderado, nuevamente usando las responsabilidades del clúster:

[Weighted sum of outer products]=

[Fraction of data point 0 represented in cluster A] * [outer product for data point 0] +
[Fraction of data point 1 represented in cluster A] * [outer product for data point 1] +
[Fraction of data point 2 represented in cluster A] * [outer product for data point 2]

=

0.007*[[59.676,20.394], [20.394,6.970]] + 
0.812*[[0.076,0.374], [0.374,1.850]] + 
0.234*[[0.526,3.364], [3.364,21.530]]

=

[[0.602, 1.234], [1.234, 6.589]]

[New covariance for cluster A] =
[[0.602,1.234], [1.234,6.589]]/1.053

=

[[0.572,1.172], [1.172,6.257]]

### Repitiendo este cálculo para el cluster B y C, llegamos a la siguiente estimación de covarianzas:

In [40]:
ex_sframe = tc.SFrame()
ex_sframe['Nuevas covarianzas'] = 'Cluster A','Cluster B','Cluster C'
ex_sframe['Cov'] = [[0.572,1.172], [1.172,6.257]],[[8.132,3.606], [3.606,2.004]], [[3.078,-0.518], [-0.518,1.581]]

print (ex_sframe)

+--------------------+-------------------------------+
| Nuevas covarianzas |              Cov              |
+--------------------+-------------------------------+
|     Cluster A      | [[0.572, 1.172], [1.172, 6... |
|     Cluster B      | [[8.132, 3.606], [3.606, 2... |
|     Cluster C      | [[3.078, -0.518], [-0.518,... |
+--------------------+-------------------------------+
[3 rows x 2 columns]



### Algoritmo EM: alternando entre E-step y M-step.

Ahora que tenemos una mejor estimación de los parámetros del clúster, regresamos nuevamente y volvemos a calcular las responsabilidades del clúster. Entonces podemos llegar a una estimación de parámetros aún mejor. De hecho, resulta que podemos alternar entre el paso E y el paso M tantas veces como queramos, y cada vez mejora la calidad del agrupamiento.